// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: action_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createActionToken = `-- name: CreateActionToken :exec
insert into action_tokens(user_id, purpose, token_hash, expires_at)
    values($1, $2, $3, $4)
returning token_id, user_id, purpose, token_hash, created_at, expires_at, used
`

type CreateActionTokenParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	Purpose   TokenPurpose `json:"purpose"`
	TokenHash []byte       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
}

func (q *Queries) CreateActionToken(ctx context.Context, arg CreateActionTokenParams) error {
	_, err := q.exec(ctx, q.createActionTokenStmt, createActionToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
