// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cleanup.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getExpiredDeletedFiles = `-- name: GetExpiredDeletedFiles :many
select file_id, storage_key, thumbnail_key
from files
    where is_deleted = true 
        and deleted_at < now()
    limit $1
`

type GetExpiredDeletedFilesRow struct {
	FileID       uuid.UUID      `json:"file_id"`
	StorageKey   string         `json:"storage_key"`
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
}

// Fetch files that have been soft-deleted for more than specific duration (e.g., 7 days)
func (q *Queries) GetExpiredDeletedFiles(ctx context.Context, limit int32) ([]GetExpiredDeletedFilesRow, error) {
	rows, err := q.query(ctx, q.getExpiredDeletedFilesStmt, getExpiredDeletedFiles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpiredDeletedFilesRow{}
	for rows.Next() {
		var i GetExpiredDeletedFilesRow
		if err := rows.Scan(&i.FileID, &i.StorageKey, &i.ThumbnailKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteFiles = `-- name: HardDeleteFiles :exec
delete from files where file_id = any($1::uuid[])
`

// Permanently remove file records
func (q *Queries) HardDeleteFiles(ctx context.Context, fileIds []uuid.UUID) error {
	_, err := q.exec(ctx, q.hardDeleteFilesStmt, hardDeleteFiles, pq.Array(fileIds))
	return err
}
