// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiScope string

const (
	ApiScopeRead  ApiScope = "read"
	ApiScopeWrite ApiScope = "write"
	ApiScopeSuper ApiScope = "super"
)

func (e *ApiScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiScope(s)
	case string:
		*e = ApiScope(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiScope: %T", src)
	}
	return nil
}

type NullApiScope struct {
	ApiScope ApiScope `json:"api_scope"`
	Valid    bool     `json:"valid"` // Valid is true if ApiScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiScope) Scan(value interface{}) error {
	if value == nil {
		ns.ApiScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiScope), nil
}

type FileVisibility string

const (
	FileVisibilityPublic  FileVisibility = "public"
	FileVisibilityPrivate FileVisibility = "private"
)

func (e *FileVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileVisibility(s)
	case string:
		*e = FileVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for FileVisibility: %T", src)
	}
	return nil
}

type NullFileVisibility struct {
	FileVisibility FileVisibility `json:"file_visibility"`
	Valid          bool           `json:"valid"` // Valid is true if FileVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.FileVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileVisibility), nil
}

type TokenPurpose string

const (
	TokenPurposeEmailVerification TokenPurpose = "email_verification"
	TokenPurposePasswordReset     TokenPurpose = "password_reset"
)

func (e *TokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenPurpose(s)
	case string:
		*e = TokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenPurpose: %T", src)
	}
	return nil
}

type NullTokenPurpose struct {
	TokenPurpose TokenPurpose `json:"token_purpose"`
	Valid        bool         `json:"valid"` // Valid is true if TokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.TokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenPurpose), nil
}

type UploadStatus string

const (
	UploadStatusPending   UploadStatus = "pending"
	UploadStatusCompleted UploadStatus = "completed"
	UploadStatusFailed    UploadStatus = "failed"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus `json:"upload_status"`
	Valid        bool         `json:"valid"` // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ActionToken struct {
	TokenID   uuid.UUID    `json:"token_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Purpose   TokenPurpose `json:"purpose"`
	TokenHash []byte       `json:"token_hash"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      bool         `json:"used"`
}

type ApiKey struct {
	ApiKeyID   uuid.UUID    `json:"api_key_id"`
	UserID     uuid.UUID    `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Prefix     string       `json:"prefix"`
	Scope      []ApiScope   `json:"scope"`
	IsRevoked  bool         `json:"is_revoked"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	ExpiresAt  time.Time    `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	LastUsedIp pqtype.Inet  `json:"last_used_ip"`
}

type File struct {
	FileID       uuid.UUID      `json:"file_id"`
	UserID       uuid.UUID      `json:"user_id"`
	Filename     string         `json:"filename"`
	StorageKey   string         `json:"storage_key"`
	MimeType     string         `json:"mime_type"`
	SizeBytes    int64          `json:"size_bytes"`
	Visibility   FileVisibility `json:"visibility"`
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
	Checksum     sql.NullString `json:"checksum"`
	Tags         []string       `json:"tags"`
	IsDeleted    bool           `json:"is_deleted"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Version      int32          `json:"version"`
}

type RefreshToken struct {
	RefreshTokenID uuid.UUID `json:"refresh_token_id"`
	UserID         uuid.UUID `json:"user_id"`
	Token          string    `json:"token"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
	Revoked        bool      `json:"revoked"`
}

type ShareLink struct {
	ShareID         uuid.UUID      `json:"share_id"`
	FileID          uuid.UUID      `json:"file_id"`
	CreatedByUserID uuid.UUID      `json:"created_by_user_id"`
	Token           string         `json:"token"`
	PasswordHash    sql.NullString `json:"password_hash"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	DownloadCount   int32          `json:"download_count"`
	CreatedAt       time.Time      `json:"created_at"`
}

type UploadSession struct {
	UploadID       uuid.UUID        `json:"upload_id"`
	UserID         uuid.NullUUID    `json:"user_id"`
	FileName       string           `json:"file_name"`
	TotalChunks    int32            `json:"total_chunks"`
	UploadedChunks sql.NullInt32    `json:"uploaded_chunks"`
	Status         NullUploadStatus `json:"status"`
	CreatedAt      sql.NullTime     `json:"created_at"`
	UpdatedAt      sql.NullTime     `json:"updated_at"`
}

type User struct {
	UserID       uuid.UUID    `json:"user_id"`
	LastName     string       `json:"last_name"`
	FirstName    string       `json:"first_name"`
	Email        string       `json:"email"`
	IsVerified   bool         `json:"is_verified"`
	Role         UserRole     `json:"role"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	LastLogin    sql.NullTime `json:"last_login"`
	Version      int32        `json:"version"`
}
